title: <p align="center"> Amaresh Mandal </p>
logo: /assets/img/logo.png
description: 
 <p align="center">
  <a href="linkedin.com/in/amareshmandal">LinkedIn</a> |
  
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
